name: "Security Report"

on:
  workflow_dispatch: # ad-hoc report generation, probably moving to a cron at some point

jobs:
  create_report:
    name: Security Scan PDF Report
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif
          full_repo_scan: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfsec.sarif
          path: ${{ github.workspace }}/tfsec.sarif

      - name: GitHub Security Report Action
        uses: peter-murray/github-security-report-action@v2
        with:
          token: ${{ github.token }}
          sarifReportDir: ${{ github.workspace }}
      
      - name: See what the report is named
        run: ls -la

      # - name: Upload Report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path:
